### PR TITLE
(feat./tweak) Added Pimax Crystal Page, organized Pimax

### PR DESCRIPTION
**Pull request by dfgHiatus**

### CODE REVIEW

**Comment by kusomaigo** [comment]
Hi dfg, could you remove the change to the yarn.lock file from the commit?

**Comment by dfgHiatus** [comment]
Done and done 👍

**Comment by kusomaigo** [comment]
Er wait, did you just delete the yarn.lock file? I think we need that 🤔

**Comment by dfgHiatus** [comment]
Omg let me fix that lmao

**Comment by dfgHiatus** [comment]
Added the current yarn.lock file from the VRCFT docs repo

**Review by kusomaigo — APPROVED** [review]
👍

**Pull request merged**
